const cats = {};



//cats["TESTCAT"] = ["000001", "000002", "000003", "000004", "000005", "000006", "000007", "000008", "000009", "000010", "000011", "000012", "000013", "000014", "000015", "000016", "000017", "000018", "000019", "000020", "000021", "000022", "000023", "000024", "000025", "000026", "000027", "000028", "000029", "000030", "000031", "000032", "000033", "000034", "000035", "000036", "000037", "000038", "000039", "000040", "000041", "000042", "000043", "000044", "000045"];

// kim-lan
			
// removed: cat, puffer, salmon (minecraft mobs), glacier (bodies of water)
cats["stardew fish"] = ["albacore", "anchovy", "angler", "bream", "bullhead", "carp", "chub", "crimson", "dorado", "eel", "flounder", "goby", "halibut", "herring", "ice pip", "largemouth bass", "lava eel", "legend", "lingcod", "mutant carp", "octopus", "perch", "pike", "radioactive carp", "rainbow trout", "red mullet", "red snapper", "sand", "sardine", "scorpion carp", "sea cucumber", "shad", "slimejack", "smallmouth bass", "spook", "stingray", "stone", "sturgeon", "sun", "tiger trout", "tilapia", "tuna", "void salmon", "walleye", "woodskip"];

cats["taylor swift songs"] = ["a perfectly good heart", "a place in this world", "better than revenge", "bigger than the whole sky", "call it what you want", "cancelled!", "come back... be here", "come in with the rain", "coney island", "dancing with our hands tied", "death by a thousand cuts", "don't blame me", "end game", "fearless", "gold rush", "hey stephen", "hoax", "holy ground", "honey", "how did it end?", "invisible", "it's nice to have a friend", "it's time to go", "jump then fall", "king of my heart", "long story short", "never grow up", "no body, no crime", "peace", "seven", "so it goes...", "superstar", "sweet nothing", "the albatross", "the best day", "the great war", "the last time", "the lucky one", "the moment i knew", "the other side of the door", "the outside", "the prophecy", "this is why we can't have nice things", "this love", "tied together with a smile"];

// removed: boo (mario enemies); boom, slurp (onomatopoeia), zombie, phantom (minecraft mobs), bomb, shield (zelda items)
cats["shy guys"] = ["barrel", "burner", "captain", "chuck", "coin bag", "dancing ghost", "door", "dreamy", "emcee", "exploring", "fly", "game", "general", "ghoul", "glide", "gourmet", "groove", "hook", "juggling", "leaf", "mace", "metal", "mummy", "ninja", "petal", "pharaoh", "pirate", "pyro", "rocket", "sergeant", "shunned", "skating", "sky", "snowboarding", "soggy", "sombrero", "spear", "spy", "stilt", "toober", "train bandit", "trampoline", "tree", "unicycle", "woozy"];

// removed: div, sub (assembly), cut for overlap with assembly
//cats["html tags"] = ["!doctype", "a", "audio", "b", "body", "br", "button", "canvas", "col", "embed", "figure", "footer", "form", "h1", "head", "header", "hr", "i", "iframe", "img", "input", "label", "li", "main", "meta", "nav", "object", "ol", "option", "p", "pre", "script", "section", "small", "span", "strong", "style", "svg", "table", "td", "template", "title", "u", "ul", "video"];

cats["musical scales & modes"] = ["acoustic", "augmented", "bebop dominant", "blues", "chromatic", "ditonic", "dorian", "double harmonic", "enigmatic", "half diminished", "harmonic", "harmonic major", "harmonic minor", "heptatonic", "hexatonic", "hungarian major", "hungarian minor", "ionian", "istrian", "locrian", "lydian", "lydian augmented", "lydian dominant", "major bebop", "major locrian", "major pentatonic", "melodic minor", "minor pentatonic", "mixolydian", "natural minor", "neopolitan minor", "non-pythagorean", "nonatonic", "octatonic", "phrygian", "phrygian dominant", "prometheus", "quarter tone", "super locrian", "tetratonic", "tritone", "tritonic", "two-semitone tritone", "ukrainian dorian", "whole tone"];

cats["coffee drinks"] = ["affogato", "bicerin", "black eye", "borgia", "breve", "cà phê sữa đá", "cafe au lait", "cappuccino", "carajillo", "caramel", "corretto", "cortado", "crema", "cubano", "dalgona", "doppio", "egg", "espresso", "flash brew", "flat white", "frappe", "irish", "karsk", "latte", "long black", "lungo", "macchiato", "marocchino", "mazagran", "melbourne magic", "melya", "miel", "mirra", "mocha", "nitro", "phin drip", "piccolo", "pour over", "qishr", "red eye", "ristretto", "turkish", "vienna", "yazdi", "zorro"];

// removed: bubble (zelda enemies)
cats["teas"] = ["ashwagandha", "assam", "bi lo chun", "boba", "buckwheat", "ceylon", "chai", "chamomile", "cherry blossom", "chrysanthemum", "chun mee", "cinnamon", "darjeeling", "earl grey", "east frisian", "echinacea", "english breakfast", "genmaicha", "ginger", "gunpowder", "gyokuro", "hao ya a", "hibiscus", "hojicha", "irish breakfast", "jasmine", "lapsang souchong", "lavender", "london fog", "longjing", "maghrebi mint", "matcha", "mint", "moroccan mint", "oolong", "orange pekoe", "pearl jasmine", "peppermint", "pu-erh", "rooibos", "rose", "sencha", "tippy yunnan", "tulsi", "turmeric"];

cats["how i met your mother episodes"] = ["46 minutes", "a change of heart", "as fast as she can", "atlantic city", "bass player wanted", "challenge accepted", "doppelgangers", "drumroll, please", "everything must go", "first time in new york", "game night", "happily ever after", "life among the gorillas", "lucky penny", "matchmaker", "milk", "mystery vs. history", "no pressure", "no questions asked", "no tomorrow", "nothing good happens after 2 a.m.", "oh honey", "okay awesome", "platonish", "right place, right time", "slap bet", "sorry, bro", "spoiler alert", "sunrise", "swarley", "sweet taste of liberty", "the broath", "the duel", "the fight", "the goat", "the leap", "the magician's code", "the pineapple incident", "the possimpible", "the scorpion and the toad", "the wedding bride", "tick, tick, tick", "wait for it", "we're not from here", "where were we?"];

cats["zelda items"] = ["beetle", "bombchu", "book of mudora", "boomerang", "bottle", "bow", "bug net", "bunny hood", "cane of somaria", "clawshot", "deku nuts", "eyeball frog", "fairy ocarina", "farore's wind", "fire rod", "fishing rod", "giant's knife", "goddess's harp", "great fairy's sword", "gust bellows", "hookshot", "hover boots", "hylian shield", "ice rod", "iron boots", "lens of truth", "longshot", "magic cape", "magic mirror", "magic powder", "mask of truth", "master sword", "mirror shield", "pegasus boots", "piece of heart", "postman's hat", "power glove", "quake medallion", "roc's feather", "sailcloth", "shovel", "slingshot", "spinner", "whip", "zora's flippers"];

// removed: bubble (teas)
cats["zelda enemies"] = ["armos", "bari", "beamos", "biri", "bokoblin", "bomskit", "bulblin", "buzzblob", "chilfos", "chuchu", "darknut", "deku baba", "dinofols", "dodongo", "floormaster", "flying pot", "flying tile", "freezard", "gibdo", "guay", "helmasaur", "iron knuckle", "kargaroc", "keese", "kodondo", "leever", "like like", "lizalfos", "moblin", "moldorm", "octorok", "peahat", "poe", "redead", "shabom", "skulltula", "staldra", "stalfos", "tailpasaran", "tektite", "torch slug", "wallmaster", "walltula", "wizzrobe", "wolfos"];

cats["strength training exercises"] = ["back extension", "bench press", "bent-over row", "bicep curl", "bird dog", "bridge", "calf raise", "chest fly", "chin up", "clean and press", "crunch", "dead bug", "deadlift", "dip", "face pull", "glute kickback", "good morning", "hip thrust", "landmine squat", "lateral raise", "leg curl", "leg extension", "leg press", "leg raise", "lunge", "mountain climber", "muscle up", "plank", "power clean", "pull down", "pull up", "push up", "pushdown", "romanian dl", "russian twist", "seated row", "shoulder press", "shrug", "sit up", "skull crusher", "squat", "sumo dl", "triceps extension", "upright row", "wrist curl"];

cats["soups"] = ["beef noodle", "bilo-billo", "binakol", "binignit", "blåbärssoppa", "borscht", "bouillabaisse", "bouillon", "bún bò huế ", "caldillo de congrio", "caldo de pollo", "callaloo", "canh chua", "canja de galinha", "česnečka", "chicken noodle", "chupe", "clam chowder", "consommé", "corn chowder", "crab bisque", "cream of mushroom", "curry mee", "egg drop", "french onion", "gazpacho", "ginataan", "gomguk", "gumbo", "hot and sour", "lobster bisque", "minestrone", "miso", "mole de olla", "oxtail", "phở", "pozole", "ramen", "samgyetang", "sinigang", "sopa de fideo", "tom yum", "tomato bisque", "vichyssoise", "zuppa toscana"];

cats["onomatopoeias"] = ["achoo", "ahem", "au au", "baa", "burp", "buzz", "bwom", "chomp", "cough", "fizz", "gâu gâu", "grrr", "guau guau", "gulp", "hiccup", "hiss", "hum", "mao", "meo", "meow", "meyaw", "miāo", "miaw", "mijav", "miov", "mjau", "mňau", "moo", "mrrr", "niau", "nyā", "quack", "ribbit", "sigh", "slosh", "slurp", "splash", "tick tock", "tsk", "tweet", "vroom", "wan wan", "whoosh", "woof", "yawn"];

// removed: marsh (orchids), glacier (stardew valley fish)
cats["bodies of water"] = ["arroyo", "basin", "bay", "bayou", "beck", "bight", "bog", "brook", "canal", "channel", "cove", "creek", "distributary", "estuary", "firth", "fjord", "gulf", "harbor", "ice cap", "ice field", "ice sheet", "inlet", "lagoon", "lake", "lick", "loch", "moat", "ocean", "pond", "pool", "port", "puddle", "reservoir", "rill", "river", "rivulet", "sea", "shoal", "sound", "spring", "strait", "stream", "swamp", "tide pool", "tributary"];

// removed: ghost (shy guys), marsh (water)
cats["orchids"] = ["bamboo", "black fiddle", "black-lipped", "blue vanda", "cattleya", "cockleshell", "common jewel", "crested snow", "cymbidium", "dancing lady", "eggleaf twayblade", "egret flower", "foul giant", "foxtail", "fried-egg", "grass pink", "holy ghost", "lady of the night", "lycaste", "masdevallia", "mayflower", "monkey-face", "moth", "noble rock", "northeastern butterfly", "phaius", "phalaenopsis", "pink cymbidium", "pink foxtail", "pink lady's slipper", "putty root", "queen victoria blue", "ruffled dancing lady", "scarlet cattleya", "showy tiger", "slipper", "sparkling jewel", "spectacular big lip", "spider", "spotted bull", "spotted cat of the mountain", "tiger-stripe", "tiger's mouth", "vanilla", "yellow cinnamon"];

// removed: cat, salmon, pufferfish (stardew valley fish), guardian (zelda enemies), zombie (shy guy)
cats["minecraft mobs"] = ["allay", "blaze", "bogged", "breeze", "cave spider", "creaking", "creeper", "drowned", "elder guardian", "ender dragon", "enderman", "endermite", "evoker", "ghast", "glow squid", "happy ghast", "hoglin", "husk", "iron golem", "magma cube", "mooshroom", "phantom", "piglin", "piglin brute", "pillager", "ravager", "shulker", "silverfish", "skeleton", "slime", "sniffer", "snow golem", "stray", "strider", "trader llama", "vex", "villager", "vindicator", "wandering trader", "warden", "witch", "wither", "wither skeleton", "zoglin", "zombie villager"];

cats["shapes"] = ["antiprism", "bifrustum", "bipyramid", "circle", "cone", "cube", "cubic honeycomb", "cupola", "dodecahedron", "ellipsoid", "gömböc", "hemicube", "hexagon", "hyperboloid", "hypercone", "hypercube", "icosahedron", "monkey saddle", "monogon", "oblate spheroid", "octagon", "octahedron", "oloid", "paraboloid", "parallelipiped", "parallelogram", "pentagon", "prism", "prismatoid", "pyramid", "rectangle", "rhombohedron", "rhombus", "snub cube", "sphere", "sphericon", "square", "squircle", "star", "tesseract", "tetrahedron", "torus", "trapezoid", "triangle", "wedge"];

cats["tabletop games"] = ["7 wonders", "above and below", "azul", "captain sonar", "clue", "codenames", "coup", "deception: murder in hong kong", "dixit", "elder sign", "exit: the game", "finspan", "flamecraft", "forbidden island", "go", "hues and cues", "love letter", "megaland", "monopoly", "munchkin", "mysterium", "outer space", "pandemic", "pictionary", "roll player", "scrabble", "secret hitler", "shadows over camelot", "skull and roses", "small world", "sorry!", "spirit island", "sushi go!", "talisman", "the game of life", "the resistance", "the settlers of catan", "ticket to ride", "tokaido", "trivial pursuit", "tsuro", "upwords", "whale to look", "wingspan", "zendo"];


// unclepunch + kim-lan

// removed: lock (art program functions), pop (onomatopoeias)
cats["assembly instructions"] = ["adc", "add", "and", "call", "cbw", "clc", "cli", "cmp", "cwd", "dec", "stc", "esc", "hlt", "idiv", "inc", "int", "iret", "jcc", "jcxz", "jmp", "lahf", "lds", "lea", "div", "loop", "mov", "mul", "neg", "not", "or", "out", "xlat", "push", "rcl", "ret", "rol", "ror", "sar", "shl", "shr", "sub", "test", "wait", "xchg", "xor"];

cats["jazz standards"] = ["actual proof", "after you've gone", "all of me", "autumn leaves", "billie's bounce", "birdland", "black orpheus", "blue bossa", "blue monk", "caravan", "chameleon", "contusion", "donna lee", "fables of faubus", "fly me to the moon", "giant steps", "groovin high", "i guess i'll hang my tears out to dry", "i want to talk about you", "it could happen to you", "it don't mean a thing", "joy spring", "la vie en rose", "mack the knife", "mercy mercy mercy", "moanin'", "mr p.c.", "my funny valentine", "night in tunisia", "on green dolphin street", "on the sunny side of the street", "softly as in a morning sunrise", "some skunk funk", "spain", "st. thomas", "strasbourg st denis", "take five", "take the a train", "teen town", "the chicken", "the girl from ipanema", "the lamp is low", "there will never be another you", "watermelon man", "wave"];


// astrevillea

// removed: mew (onomatopoeias)
cats["pokémon"] = ["wattrel", "meditite", "calyrex", "type: null", "zarude", "nymble", "shroodle", "seel", "fezandipiti", "iron crown", "walking wake", "wo-chien", "alakazam", "mewtwo", "great tusk", "spoink", "bidoof", "drapion", "stoutland", "golem", "klang", "iron treads", "kingambit", "durant", "heliolisk", "tyrunt", "scream tail", "brionne", "mudsdale", "comfey", "minior", "tapu fini", "blacephalon", "zeraora", "wooloo", "carkol", "eiscue", "drakloak", "glastrier", "ursaluna", "enamorus", "squawkabilly", "rellor", "espathra", "houndstone"];

cats["mario kart tracks"] = ["water park", "sunshine airport", "acorn heights", "cloudtop cruise", "bowser’s castle", "sweet sweet canyon", "dolphin shoals", "faraway oasis", "peach stadium", "toad’s turnpike", "thwomp ruins", "starview peak", "electrodome", "mount wario", "rainbow road", "crown city", "cheep cheep beach", "royal raceway", "dino dino jungle", "peach beach", "whistlestop summit", "shy guy falls", "dk spaceport", "toad harbor", "desert hills", "wario stadium", "great ? block ruins", "dandelion depths", "music park", "sherbet land", "twisted mansion", "boo cinema", "dry bones burnout", "moo moo meadows", "tick-tock clock", "choco mountain", "toad’s factory", "piranha plant slide", "grumble volcano", "new york minute", "kalimari desert", "maple treeway", "riverside park", "singapore speedway", "koopa cape"];

cats["genshin impact playable characters"] = ["gaming", "jean", "aether", "yunjin", "lumine", "diluc", "neuvillette", "charlotte", "iansan", "skirk", "tartaglia", "amber", "noelle", "barbara", "razor", "candace", "columbina", "cyno", "dori", "dahlia", "emilie", "escoffier", "flins", "ifa", "kaeya", "klee", "layla", "lisa", "lyney", "lynette", "navia", "qiqi", "ororon", "yaemiko", "sucrose", "venti", "xiao", "yaoyao", "yelan", "xianyun", "ayaka", "ayato", "kazuha", "mizuki", "shinobu"];


// frogwarrior

cats["cat breeds"] = ["abyssinian", "aegean", "oriental bicolor", "american curl", "ragamuffin", "american wirehair", "aphrodite giant", "arabian mau", "russian blue", "asian semi-longhair", "austrialian mist", "balinese", "scottish fold", "bengal", "birman", "bombay", "brazilian shorthair", "british longhair", "siamese", "burmese", "burmilla", "california spangled", "chantilly-tiffany", "chartreux", "chausie", "colorpoint shorthair", "snowshoe", "cymric", "cyprus", "thai lilac", "donskoy", "domestic shorthair", "egyptian mau", "somali", "exotic shorthair", "turkish van", "havana brown", "highlander", "himalayan", "japanese bobtail", "javanese", "turkish angora", "korat", "tonkinese", "singapura"];

// removed: starman (earthbound), tac, wheelie (city trial events)
cats["kirby enemies"] = ["beanbon", "waddle dee", "waddle doo", "bronto burt", "cappy", "blipper", "broom hatter", "glunk", "gordo", "kabu", "grizzo", "mumbles", "poppy bros. jr.", "scarfy", "sir kibble", "squishy", "blade knight", "bomber", "flamer", "hot head", "rocky", "sparky", "dale", "batamon", "birdon", "knuckle joe", "n-z", "walky", "galbo", "pacto", "cupie", "mummbon", "oohroo", "zombon", "snoozroot", "beetley", "spynum", "cotta", "awoofy", "bernard", "buffahorn", "digguh", "sandran", "whippy", "walf"];


// frogwarrior (+ friends) and sutie

// cut for overlap with 3ds games
//cats["turn based games"] = ["final fantasy", "breath of fire", "mario & luigi", "paper mario", "super mario rpg", "chrono trigger", "fire emblem", "pokémon", "earthbound", "xenoblade", "xenogears", "miitopia", "the world ends with you", "dragon quest", "secret of mana", "octopath traveler", "bravely default", "neir", "megaman battle network", "golden sun", "sea of stars", "final fantasy tactics", "mario + rabbids", "saga", "persona", "kingdom hearts", "shin megami tensei", "monster hunter", "yo-kai watch", "phantasy star", "digimon", "bug fables", "undertale", "deltarune", "metaphor: refantazio", "baldur's gate", "everhood", "clair obscur: expedition 33", "xcom", "darkest dungeons", "omori", "ni no kuni", "lost odyssey", "skies of arcadia", "baten kaitos"];


// shinylurantis

cats["minecraft songs"] = ["subwoofer lullaby", "living mice", "haggstrom", "oxygene", "mice on venus", "dry hands", "wet hands", "clark", "sweden", "danny", "blind spots", "biome fest", "haunt muskie", "aria math", "taswell", "dreiton", "ballad of the cats", "concrete halls", "dead voxel", "warmth", "chrysopoeia", "rubedo", "so below", "beginning 2", "floating trees", "moog city 2", "mutation", "stand tall", "left to bloom", "ancestry", "wending", "infinite amethyst", "one more day", "floating dream", "comforting memories", "13", "cat", "blocks", "chirp", "far", "mall", "mellohi", "stal", "strad", "ward"];

cats["mexican cities"] = ["tijuana", "ensenada", "mexicali", "la paz", "hermosillo", "puerto peñasco", "guaymas", "nogales", "chihuahua", "ciudad juarez", "saltillo", "monterrey", "nuevo laredo", "matamoros", "tampico", "san luis potosi", "durango", "cualican", "mazatlan", "tepic", "puerto vallarta", "guadalajara", "colima", "morelia", "guanajuato", "queretaro", "pachuca", "toluca", "mexico", "cuernavaca", "chilpancingo", "acapulco", "puebla", "tlaxcala", "oaxaca", "veracruz", "xalapa", "villahermosa", "tuxtla gutierrez", "campeche", "merida", "cancun", "chetumal", "playa de carmen", "tapachula"];


// cobis

cats["super mario sunshine shines"] = ["a golden bird", "crate game 1", "the gold bird", "soak the sun", "lighthouse roof", "father and son shine!", "pachinko", "lily pad ride", "the watermelon festival", "chain chomplets unchained", "chain chomp's bath", "the secret of the dirty lake", "dune bud sand castle secret", "mirror madness! tilt, slam, bam!", "wiggler ahoy! full steam ahead!", "the sand bird is born", "the goopy inferno", "eely-mouth's dentist", "gooper blooper breaks out", "gooper blooper returns", "blooper surfing safari", "blooper-surfing sequel", "clean the west bell", "clean the east bell", "the boss of tricky ruins", "road to the big windmill", "the hillside cave secret", "the beach cannon's secret", "the wilted sunflowers", "the runaway ferris wheel", "roller coaster balloons", "the manta storm", "the hotel lobby's secret", "uncork the waterfall", "the shell's secret", "secret of the village underside", "fluff festival coin hunt", "down with petey piranha!", "hold it, shadow mario!", "yoshi's fruit adventure", "mecha-bowser appears!", "red coins in the yoshi-go-round", "il piantissimo's crazy climb", "piantas in need", "scrubbing sirena beach"];


// sutie

cats["wii sports resort stamps"] = ["cliff-hanger", "straight to the point", "met your match", "one hit wonder", "slice and dice", "a cut above", "huge air", "bag of tricks", "the long way home", "a for effort", "lucky skip", "straight and narrow", "bull stampede", "a secret to everybody", "bonus plumber", "buzzer beater", "in your face", "back from the brink", "perfectly matched", "recycler", "save face", "king of clubs", "gobble gobble", "high roller", "off the wall", "secret strike", "one for all", "head first", "english major", "ringmaster", "leisure cruiser", "beginner license", "ducks in a row", "cut the red tape", "last gasp", "first of many", "6-stage master", "high five", "for the birds", "friends in high places", "camera shy", "island hopper", "pop frenzy", "follow that plane", "split spare"];

cats["jackbox games"] = ["quiplash", "trivia murder party", "tee k.o.", "drawful", "fibbage", "lie swatter", "word spud", "bomb corp.", "earwax", "fakin' it", "guesspionage", "survey scramble", "bracketeering", "civic doodle", "monster seeking monster", "survive the internet", "mad verse city", "patently stupid", "split the room", "zeeple dome", "dictionarium", "joke boat", "push the button", "role models", "blather 'round", "champ'd up", "talking points", "the devils and the details", "job job", "the poll mine", "the wheel of enormous proportions", "weapons drawn", "junktopia", "nonsensory", "quizort", "roomerang", "dodo re me", "fixytext", "hypnotorious", "time jinx", "suspectives", "doominate", "legends of trivia", "cookie haus", "hear say"];

// cut for overlap with fish, lavas, and others
//cats["color thread type colors"] = ["chartreuse", "mauve", "taupe", "vermillion", "zaffre", "puce", "gamboge", "aureolin", "caesious", "solferino", "patina", "aubergine", "viridian", "auburn", "alabaster", "ochre", "pewter", "timberwolf", "teal", "aqua", "turquoise", "cinnabar", "heliotrope", "sable", "slate", "sanguine", "burnt umber", "carnelian", "onyx", "russet", "azure", "citrine", "saffron", "harlequin", "heather", "grizzle", "gainsboro", "ecru", "bay", "beaver", "ultramarine", "verdigris", "tawny", "flaxen", "jonquil"];

cats["pplushie realm movie streams"] = ["5 centimeters per second", "a bug's life", "a goofy movie", "a silent voice", "an extremely goofy movie", "animal crossing: the movie", "barbie", "camp rock", "castle in the sky", "digimon: the movie", "everything everywhere all at once", "finding dory", "finding nemo", "flow", "how to train your dragon", "howl's moving castle", "interstellar", "kiki's delivery service", "klaus", "lemonade mouth", "lilo & stitch", "mean girls", "meet the robinsons", "megamind", "only yesterday", "ratatoullie", "redline", "saving face", "scott pilgrim vs. the world", "season of love", "sky high", "spider-man: into the spider-verse", "super mario bros.", "suzume", "the adventures of sharkboy and lavagirl", "the land before time x", "the nightmare before christmas", "the place promised in our early days", "the secret world of arrietty", "up", "weathering with you", "whisper of the heart", "wicked", "wicked: for good", "your name"];

cats["hiragana"] = ["あ", "い", "う", "え", "お", "か", "き", "く", "け", "こ", "さ", "し", "す", "せ", "そ", "た", "ち", "つ", "て", "と", "な", "に", "ぬ", "ね", "の", "は", "ひ", "ふ", "ん", "ほ", "ま", "み", "む", "め", "も", "や", "ゆ", "よ", "ら", "り", "る", "れ", "ろ", "わ", "を"];

cats["katakana"] = ["ア", "イ", "ウ", "エ", "オ", "カ", "キ", "ク", "ケ", "コ", "サ", "シ", "ス", "セ", "ソ", "タ", "チ", "ツ", "テ", "ト", "ナ", "ニ", "ヌ", "ネ", "ノ", "ハ", "ヒ", "フ", "ン", "ホ", "マ", "ミ", "ム", "メ", "モ", "ヤ", "ユ", "ヨ", "ラ", "リ", "ル", "レ", "ロ", "ワ", "ヲ"];

// removed: monch, sip, sniff (onomatopoeias)
cats["pplushie realm emotes"] = ["7", "bounce", "comfy", "confused", "cool", "cry", "dance", "ez", "fall", "flat", "flushed", "gn", "hi", "hug", "hype", "jam", "kaawiz", "love", "lurk", "melted", "froge", "noted", "ok", "pain", "party", "pensive", "plead", "pog", "polite", "relieved", "roll", "flatter", "sit", "sitintraffic", "sleep", "smol", "eyecontact", "stand", "sweat", "shy", "swim", "thinkies", "uh", "v", "vibe"];

cats["stream titles"] = ["idk what's going on but we have brick road", "happy happy worry worry", "tumbling around at the speed of sound!", "getting rolled by this game", "sleepier than noddy and sleep kirby", "happy year of the honse", "yearning for yarn", "shhhh the island is sleeping", "what secrets remain..?", "midna & the amazing mirror", "beyblade master vs the world", "link is a good boy & so cute", "welcome to the twilight zone", "woof woof bark bark", "is it hot in here or do i have a fever", "volcano and foster kittens", "i am once again a dogy", "please do not the pikmin", "pikmin sighing sound effect", "vacuuming our problems away", "three of them!!!", "fiending for fruit!", "pls give back our juice", "i fear the night", "summertime in the third area", "oatchi is everything!", "spring breaking on wuhu island", "the final yoshi!?", "let's yoshi this island", "feeling alive in world 5", "touching fuzzy and getting dizzy", "yoshi wants macaroni and cheese", "flan-powered flower collecting", "pink link vs the world", "swimmies in water land!", "snow day? snow problem", "milky way wishes but it's yarn", "kirby's return to yarn land", "downloading lor lore", "it's always a good time for cake", "shy village, dinosaurs, and more", "journeyed to the center of the earth!", "how is this game so amazing", "trying to chill during this heat wave", "pikmin in your living room!"];

// cut for overlap with peak items and lava flavors
//cats["air riders food pngs"] = ["apple", "bananas", "bread basket", "cake slice", "cake", "cheese", "cheeseburger", "double cheeseburger", "chocolate", "cola", "cupcake", "donuts", "dumpling", "omurice", "french fries", "fried rice", "fruit basket", "gelatin", "grapes", "hamburg steak", "hot dog", "icecream", "jelly beans", "lettuce", "melon cream soda", "plate of nigiri", "board of nigiri", "orange", "orange juice", "pancakes", "parfait", "spaghetti", "pizza", "popcorn", "ramen", "salad", "sambusas", "sandwich", "shaved ice", "rainbow shaved ice", "steak", "tempura bowl", "watermelon slice", "watermelon"];

cats["steven universe season one"] = ["political power", "the return", "jail break", "gem glow", "laser light cannon", "cheeseburger backpack", "together breakfast", "frybo", "cat fingers", "bubble buddies", "serious steven", "tiger millionaire", "steven's lion", "arcade mania", "giant woman", "so many birthdays", "lars and the cool kids", "onion trade", "steven the sword fighter", "rose's room", "coach steven", "joking victim", "steven and the stevens", "monster buddies", "an indirect kiss", "mirror gem", "ocean gem", "house guest", "space race", "secret team", "island adventure", "keep beach city weird!", "fusion cuisine", "watermelon steven", "warp tour", "alone together", "the test", "future vision", "on the run", "horror club", "winter forecast", "maximum capacity", "marble madness", "rose's scabbard", "the message"];

// removed: starman (kirby)
cats["earthbound enemies"] = ["abstract art", "armored frog", "atomic power robot", "attack slug", "bad buffalo", "black antoid", "care free bomb", "coil snake", "crested booka", "dali's clock", "ego orb", "electro swoosh", "enraged fire plug", "fobby", "hyper spinning robo", "kiss of death", "lesser mook", "li'l ufo", "loaded dice", "mad duck", "mad taxi", "mechanical octobot", "mobile sprout", "mole playing rough", "mr. batty", "mystical record", "new age retro hippie", "nuclear reactor robot", "pogo punk", "putrid moldyman", "ramblin' evil mushroom", "ranboob", "robo-pump", "scalding coffee cup", "smilin' sphere", "soul consuming flame", "spinning robo", "spiteful crow", "foppy", "tangoo", "territorial oak", "unassuming local guy", "whirling robo", "wooly shambler", "worthless protoplasm"];

cats["starbound figurine creatures"] = ["anglure", "batong", "bobfae", "bobot", "bulbop", "capricoat", "crabcano", "crustoise", "fennix", "gosmet", "hypnare", "ignome", "iguarmor", "ixoling", "lilodon", "lumoth", "miasmop", "monopus", "narfin", "oculob", "orbide", "peblit", "petricub", "pipkin", "poptop", "pteropod", "pulpin", "pyromantle", "quagmutt", "ringram", "scaveran", "skimbus", "smoglin", "snaggler", "snaunt", "spookit", "squeem", "taroni", "tintic", "toumingo", "trictus", "triplod", "voltip", "wisper", "yokat"];

cats["lava flavors"] = ["tic tac and orange skittles", "cherry syruped meat", "flat orange soda", "bright and tangy", "flat and dull", "from concentrate", "one-tone", "gatorade", "firefly soup", "burnt pancakes", "bright citrusy", "pizza", "grape ??", "diced raw pineapples", "not fully baked", "grilled appl", "maple bacon", "overwhelmingly sour", "brownie fudge with zest", "bland cheerio dust", "spicy nacho cheese doritos", "pomegranate", "fruit leather", "pepperoni", "finest but it sucks", "water + various chip dust", "melty cheeese sauce", "fabric", "empty", "chream cheese marinara sauce", "thick and tangy", "panera charged lemonade", "fresh fruit juice", "rasins", "chili powdered carrot cake", "fruit punch but dim", "burnt cinammon", "crunchy tortilla chips", "scary viscous egg yolks", "citrusy zesty", "bloom", "spicy soup", "red leds", "cherry 7up", "hue-shifted beef jerky"];

cats["peak items"] = ["airline food", "ancient idol", "anti-rope", "antidote", "balloon", "bandages", "big lollipop", "blowgun", "bounce fungus", "bugle", "chain launcher", "checkpoint flag", "cloud fungus", "cure-all", "cursed skull", "hot dog", "energy drink", "faerie lantern", "first aid kit", "fortified milk", "granola bar", "heat pack", "honeycomb", "big egg", "magic bean", "marshmallow", "medicinal root", "napberry", "pandora's lunchbox", "parasol", "pirate's compass", "piton", "portable stove", "remedy fungus", "rescue claw", "scorchberry", "scout cannon", "scout cookies", "scout effigy", "shelf fungus", "sports drink", "strange gem", "sunscreen", "the book of bones", "trail mix"];

// removed: steven universe, avatar the last airbender, over the garden wall (server streams), cut for excess
//cats["modern kids cartoons"] = ["the powerpuff girls", "the owl house", "gravity falls", "amphibia", "we bare bears", "adventure time", "clarence", "infinity train", "ok k.o.! let's be heroes", "miraculous ladybug", "hilda", "craig of the creek", "regular show", "wander over yonder", "star vs the forces of evil", "summer camp island", "phineas and ferb", "the loud house", "the amazing world of gumball", "kim possible", "the marvelous misadventures of flapjack", "courage the cowardly dog", "samurai jack", "codename: kids next door", "foster's home for imaginary friends", "camp lazlo", "my gym partner's a monkey", "chowder", "ben 10", "mao mao: heroes of pure heart", "the grim adventures of billy & mandy", "the adventures of jimmy neutron", "the fairly oddparents", "danny phantom", "rugrats", "invader zim", "spongebob squarepants", "rocko's modern life", "johnny bravo", "dexter's laboratory", "ed, edd n eddy", "cow and chicken", "uncle grandpa", "my life as a teenage robot", "chalkzone"];

cats["game consoles"] = ["odyssey", "color tv-game", "game & watch", "2600", "5200", "intellivision", "colecovision", "famicom", "entertaniment system", "master system", "7800", "turbografx-16", "mega drive", "genesis", "cd-i", "neo geo", "game boy", "lynx", "game gear", "64", "saturn", "playstation", "3do", "jaguar", "virtual boy", "dreamcast", "gamecube", "xbox", "advance", "wonderswan", "n-gage", "pokémon mini", "leapster", "360", "wii", "ds", "psp", "one", "switch", "vita", "series x/s", "ouya", "stadia", "quest", "vive"];

// cut for overlap with html tags and assembly
//cats["file formats"] = ["gif", "png", "jpg", "exe", "zip", "bat", "rar", "7z", "apk", "msi", "bin", "iso", "mp3", "mp4", "wav", "mov", "psd", "pdf", "epub", "psd", "txt", "docx", "rtf", "bmp", "webp", "webm", "swf", "otf", "ttf", "stl", "svg", "json", "html", "js", "py", "dat", "tmp", "avi", "xml", "ogg", "blend", "obj", "fbx", "jar", "flac"];

// removed: circle, line, ellipse (shapes), zoom (onomatopoeias)
cats["art program functions"] = ["cut", "copy", "paste", "scale", "crop", "shear", "rotate", "save", "load", "import", "export", "undo", "redo", "brush", "pencil", "select", "layer", "opacity", "hue", "brightness", "saturation", "contrast", "flatten", "liquify", "shape", "pressure", "magic wand", "warp", "filter", "onion skin", "merge", "flip", "eraser", "eyedropper", "mask", "blur", "smear", "burn", "dodge", "lasso", "airbrush", "palette", "gradient", "fill", "text"];

cats["paper mario badges"] = ["all or nothing", "attack fx a", "bump attack", "chill out", "close call", "d-down pound", "damage dodge", "deep focus", "defend plus", "dizzy attack", "dodge master", "double dip", "feeling fine", "fire shield", "first attack", "flower finder", "group focus", "hammer throw", "happy heart", "hp plus", "i spy", "ice power", "jump charge", "last stand", "lucky day", "mega quake", "money money", "multibounce", "p-up, d-down", "pay-off", "power bounce", "power plus", "pretty lucky", "quake hammer", "quick change", "refund", "runaway pay", "s. jump charge", "shrink stomp", "slow go", "smash charge", "speedy spin", "spike shield", "spin attack", "zap tap"];

cats["mario party jamboree minigames"] = ["lumber tumble", "big-top quiz", "camera-ready", "scare-ousel", "snag the flags", "sandwiched", "hot cross blocks", "light-wave battle", "thwomp the difference", "cold front", "hot-hot hop", "domination", "three throw", "granite getaway", "tilt-a-golf", "night lights", "hammer it home", "twist and sort", "shuttle scuttle", "tiny triathlon", "pickax dash", "gate key-pers", "sled to the edge", "rinks to riches", "treetop treasure", "treasure divers", "platform peril", "stamp out!", "trample-line", "sunset standoff", "cookie cutters", "unfriendly flying object", "lost and pound", "arch rivals", "on-again, off-again", "broozer bash", "cage catch", "income stream", "blame it on the crane", "snow brawl", "squeaky shakedown", "rocky rope race", "pickin' produce", "prime cut", "dorrie pedal-paddle"];

cats["city trial field events"] = ["air ride machine formation", "dyna blade's swooping in", "fake patches", "dense fog", "huge pillars", "item bounce", "lighthouse turned on", "danger! huge meteors", "rail station fire", "restoration areas", "no fair! same items", "secret rooms opened", "stadium prediction", "energy tanks run amok", "band of tacs stole items", "mysterious u.f.o.", "battleship halberd", "machines about to break", "cracked boxes all over", "increased dash zones", "dustup derby", "can't stop doing quick spins", "fake rare boxes", "flipped controls", "machines fly more easily", "giant items", "gordos falling from the sky", "grand wheelie's roaring down the road", "machines pulled by gravity", "rails lined with items", "kracko's thundered onto the scene", "reward rings", "machines in the parking lot", "rush to the portals", "raining boxes", "rare boxes", "short race", "slippery ground", "tiny boxes", "everyone is tiny", "treasure chests", "treasure stars", "everyone's riding ufos", "destroy vacant machines", "wild legendary machine"];

// cut for overlap with onomatopoeias
//cats["animal crossing gyroids"] = ["gargl", "warbl", "freak", "ech", "gong", "polterg", "lament", "metat", "squelch", "fizz", "plink", "croak", "strumb", "rust", "buzz", "timpan", "dekk", "drill", "ob", "all", "dink", "dropl", "harmon", "toot", "howl", "bowt", "nebul", "dingl", "puff", "lullab", "percol", "spr", "rhythm", "oombl", "bov", "sputn", "quaz", "brewst", "arf", "bend", "doot", "jingl", "thwomp", "xyloph", "ll"];

// cut for labal overlap with html tags, and for excess
//cats["animal crossing characters"] = ["blanca", "don resetti", "gulliver", "joan", "k.k. slider", "mr. resetti", "pascal", "redd", "rover", "saharah", "wendell", "wisp", "blathers", "brewster", "celeste", "cyrus", "digby", "shrunk", "gracie", "harriet", "harvey", "isabelle", "kapp'n", "katrina", "kicks", "label", "leif", "lloid", "lyle", "mabel", "orville", "pelly", "pete", "phyllis", "porter", "reese", "sable", "timmy", "tommy", "tom nook", "tortimer", "wilbur", "zipper", "c.j.", "flick"];


// side angle cj
cats["3ds games"] = ["paper mario: sticker star", "kirby: planet robobot", "professor layton vs phoenix wright", "animal crossing: new leaf", "tri force heroes", "boxboy!", "chibi-robo! zip lash", "luigi's mansion: dark moon", "detective pikachu", "mario party: island tour", "monster hunter stories", "miitopia", "pokemon picross", "garfield kart", "harmoknight", "brain age: concentration training", "freakyforms: your creations, alive!", "mario tennis open", "kid icarus: uprising", "dillon's rolling western", "mario kart 7", "warioware gold", "yo-kai watch", "radiant historia", "rhythm heaven megamix", "pokemon rumble world", "ultimate nes remix", "shovel knight", "tomodachi life", "yoshi's new island", "steel diver", "wipeout: create & crash", "pokemon alpha sapphire", "new super mario bros. 2", "nintendogs + cats", "donkey kong country returns 3d", "hey! pikmin", "a link between worlds", "metroid: samus returns", "ever oasis", "rhythm thief", "kirby: triple deluxe", "xenoblade chronicles 3d", "fire emblem: awakening", "mario & luigi: dream team"];